vich_uploader:
    db_driver: orm

    # mappings:
    #   property_image:
    #     uri_prefix: /images/dg
    #     upload_destination: '%kernel.project_dir%/public/images/dg'
    #     namer : Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'


    mappings:
      vehicules_image:
          # uri_prefix: '%vehicules_directory%'
          # upload_destination: '%vehicules_directory%' 
          uri_prefix: '%vehicules_directory%'
          upload_destination: '%kernel.project_dir%/public/%vehicules_directory%'

